name: mac

on:
  push:
    branches: "*"
    tags: "*"

jobs:
  build:
    runs-on: [macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: configure
        run: cmake . -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release 
      
      - name: build
        run: cmake --build build --parallel

      - name: install
        run: cmake --build build --target package

      - name: 'upload artifact'
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: ClapWorkbenchSDK
          path: "build/*.tar.gz"
          if-no-files-found: error

      - name: Upload to GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: "build/*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
