name: CI

on:
  push:
    branches: "*"
    tags: "*"

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure
        run: cmake . -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release
        env:
          MACOSX_DEPLOYMENT_TARGET: 12.0.0 # temp fix, needed by Qt
      
      - name: Build
        run: cmake --build build --parallel

      - name: Package
        run: cmake --build build --target package

      - name: Upload artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: ClapWorkbenchSDK-${{ matrix.os }}
          path: "build/*.tar.gz"
          if-no-files-found: error

      - name: Upload to GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: "build/*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
