name: mac

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: setup dependencies
        run: brew install ninja
      
      - name: configure
        run: cmake . -B build -GNinja -DCMAKE_BUILD_TYPE=Release 
      
      - name: build
        run: cmake --build build --parallel

      - name: install
        run: cmake --install build

      - name: 'upload artifact (MacOS)'
        if: runner.os == 'MacOS'
        uses: actions/upload-artifact@v4
        with:
          name: ClapWorkbenchSDK (MacOS)
          path: build/_install
          if-no-files-found: error
